unicorn-hal/unicorn-monorepo

- api-server/src/main/kotlin/com/unicorn/api/application_service/greeting/SaveGreetingService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/greeting/GreetingController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/greeting/Greeting.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/greeting/GreetingRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/greeting/GreetingPostTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/greeting/GreetingTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/greeting/GreetingRepositoryTest.kt
https://www.notion.so/POST-API-25b79677e12245a787244bb11f1d64b9?pvs=4
- API実装
- テスト記述
- テストにて動作確認
> POST Greeting API実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/greeting/UpdateGreetingService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/greeting/GreetingController.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/greeting/GreetingRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/greeting/GreetingPutTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/greeting/GreetingRepositoryTest.kt
https://www.notion.so/PUT-API-82d2db787916444e8bbd468959d9cad4?pvs=4
- API実装
- Repositoryのテストケース追加
- APIテスト追加
- テストが正常に通ること
> feat: update greeting api

- api-server/src/main/kotlin/com/unicorn/api/application_service/greeting/DeleteGreetingService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/greeting/GreetingController.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/greeting/GreetingRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/greeting/GreetingDeleteTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/greeting/GreetingRepositoryTest.kt
- api-server/src/test/resources/db/greeting/Insert_Greeting_Data.sql
このセクションでは、このPRの目的と概要を簡潔に説明してください。
- 変更点1
- 変更点2
- 変更点3
> feat: delete api 実装

- .circleci/config.yml
- README.md
- api-server/src/main/resources/application-test.properties
> CircleCI Commit

- .idea/dataSources.xml
- .idea/sqldialects.xml
- api-server/src/main/kotlin/com/unicorn/api/domain/account/Account.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/account/AccountRepository.kt
- api-server/src/main/resources/db/migration/V021__Rename_DeletedAt_to_deleted_at.sql
- api-server/src/test/kotlin/com/unicorn/api/domain/account/AccountTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/account/AccountRepositoryTest.kt
- api-server/src/test/resources/db/account/Insert_Account_Data.sql
- POST, PUT DELETEを行うためのDomain, Repository実装
- Domain実装
- Repository実装
- テスト記述
- ideaのDBリリースファイル追加
- テストが正常に通ること
> アカウントのDomain・Repository実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/account/DeleteAccountService.kt
- api-server/src/main/kotlin/com/unicorn/api/application_service/account/SaveAccountService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/account/AccountController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/account/Account.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/account/AccountRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/account/AccountDeleteTest.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/account/AccountPostTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/account/AccountRepositoryTest.kt
Account削除APIの実装と、論理削除に伴うリポジトリの修正
- API実装
- テスト記述
- Reposiitory修正
- ローカルでの動作確認
> Account削除API実装&Repository修正

- api-server/src/main/resources/db/migration/V023__Create_AppConfig_Table.sql
AppConfigテーブルのマイグレーションファイル実装
- AppConfigテーブルの作成
- ./gradlew flywayCleanの成功
- ./gradlew flywayMigrateの成功
- ./gradlew bootRunの成功
- DBeaverにてテーブルが作成されていることの確認
- AppConfigテーブルが作成されていること
> AppConfigテーブルのマイグレーションファイル実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/user/SaveUserService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/api_response/api_response.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/user/UserController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/user/UserPostTest.kt
https://www.notion.so/POST-users-cd95454fd0ab477e8b883002732dad2c?pvs=4
- User登録API実装
- テスト記述
- ResponseErrorの共通クラス定義
-  テストが正常に通ること
> ユーザー登録APIの実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/user/UpdateUserService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/user/UserController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/user/User.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/user/UserPutTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/user/UserTest.kt
https://www.notion.so/PUT-users-userID-8aa42c13c4264811bba0b5c7dc4b394b?pvs=4
- API実装
- テスト記述
- Userドメイン修正
- テストが正常に通ること
> ユーザー更新APIの実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/user/DeleteUserService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/user/UserController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/user/UserDeleteTest.kt
https://www.notion.so/DELETE-users-userID-b9c5a2c64bcd40fa848ab14fc6c67f07?pvs=4
- ユーザ削除API実装
- テスト記述
- テストが正常に通ること
> ユーザー削除API実装

- .idea/sqldialects.xml
- api-server/src/main/kotlin/com/unicorn/api/controller/user/UserController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/user/UserQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/user/UserDeleteTest.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/user/UserGetTest.kt
- api-spec/api-spec.yaml
- api-stub-server/api/openapi.yaml
- api-stub-server/service/UserService.js
https://www.notion.so/GET-users-API-053bc0efd5d14b52a7bf6d86c90d6a03?pvs=4
- ユーザー取得API実装
- テスト記述
- DeleteTestの不要な行を削除
- テストが正常に通ること
> ユーザー取得API実装

- api-server/src/main/kotlin/com/unicorn/api/domain/medicine/Medicine.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/medicine/MedicineRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/medicine/MedicineTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/medicine/MedicineRepositoryTest.kt
- api-server/src/test/resources/db/medicine/Insert_Medicine_Data.sql
medicine API のdomain・repository実装
- Medicine.kt と MedicineRepository.kt を追加。
- domain と repository それぞれのテストファイルを追加。
- テスト用の Insert 文を追加。
- テストが通ることを確認。
> [TSK-202] medicine API のdomain・repository実装

- api-server/src/main/kotlin/com/unicorn/api/domain/family_email/FamilyEmail.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/family_email/FamilyEmailRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/family_email/FamilyEmailTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/family_email/FamilyEmailRepositoryTest.kt
- api-server/src/test/resources/db/family_email/Insert_FamilyEmail_Data.sql
family_emailのdomain・repository実装
- domainのFamilyEmail.ktとrepositoryのFamilyEmailRepository.ktの追加
- domain,repositoryそれぞれのテストファイル追加
- テスト用Insert文追加
- テストが通ることを確認
> [TSK-201] family_emailのdomain・repository実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/medicine/SaveMedicineService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/medicine/MedicineController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/medicine/Medicine.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/medicine/MedicineRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/medicine/MedicinePostTest.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/medicine/MedicinesGetTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/medicine/MedicineTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/medicine/MedicineRepositoryTest.kt
- api-server/src/test/resources/db/medicine/Insert_Medicine_Data.sql
おくすり情報登録機能の実装（post）
- MedicineController に追記
- SaveMedicineService の追加
- 対応するテストの追加
- MedicineRepository 内の userID の型を UserID から UID に変更
- テストが成功すること。
> [TSK-190] おくすり情報登録機能の実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/family_email/UpdateFamilyEmailService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/family_email/FamilyEmailController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/family_email/FamilyEmailPutTest.kt
- 家族メールアドレス情報を更新できるAPIを実装する
- 家族メールアドレスが適切に更新できているかどうかを確認するテストを行う
- controllerのFamilyEmailController.ktに更新の機能を追加
- applicationserviceのUpdateFamilyEmailService.ktを追加
- PUTのテストを行うFamilyEmailPutTest.ktを追加
- テストが通ったことを確認
- ローカル環境で更新ができたことを確認
> [TSK-187] family_emailのPUT実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/medicine/UpdateMedicineService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/medicine/MedicineController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/medicine/MedicinePutTest.kt
おくすり情報更新機能の実装
- MedicineController に追記。
- UpdateMedicineService を追加。
- テストを追加。
- テストが通ること。
> [TSK-191] おくすり情報更新機能の実装

- api-server/build.gradle.kts
- api-server/src/main/kotlin/com/unicorn/api/domain/doctor/Doctor.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/doctor/DoctorRepository.kt
- api-server/src/main/resources/db/migration/V024__Refactor_Doctor_Table.sql
- api-server/src/main/resources/db/migration/V025__Refactor_Doctor_Department_Table.sql
- api-server/src/test/kotlin/com/unicorn/api/domain/doctor/DoctorTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/doctor/DoctorRepositoryTest.kt
- api-server/src/test/resources/db/account/Insert_Account_Data.sql
- api-server/src/test/resources/db/doctor/Insert_Deleted_Doctor_Data.sql
- api-server/src/test/resources/db/doctor/Insert_Doctor_Data.sql
- api-server/src/test/resources/db/doctor/Insert_Parent_Account_Data.sql
- api-server/src/test/resources/db/doctor_department/Insert_Doctor_Department_Data.sql
DoctorAPIのドメインとリポジトリ実装
- Doctorのドメイン実装
- Docotorのリポジトリ実装
- AccountSQLの修正
- テスト記述
- テストが通ること
- 皇族で、Call と Chatのドメイン実装が行えていること
> DoctorのDomain infra実装

- .idea/uiDesigner.xml
- api-server/src/main/kotlin/com/unicorn/api/domain/call_support/CallSupport.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/chat_support/ChatSupport.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/call_support/ChatSupportRepository.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/chat_support/CallSupportRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/call_support/CallSupportTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/chat_support/ChatSupportTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/call_support/CallSupportRepositoryTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/chat_support/ChatSupportRepositoryTest.kt
- api-server/src/test/resources/db/call_support/Insert_Call_Support_Data.sql
- api-server/src/test/resources/db/call_support/Insert_Parent_Doctor_Data.sql
- api-server/src/test/resources/db/chat_support/Insert_Chat_Support_Data.sql
- api-server/src/test/resources/db/chat_support/Insert_Parent_Doctor_Data.sql
call supportとchat supportのDomain Repository実装
- chat support と call support のdomain repository実装
- テスト記述
- テストが通ること
> ChatとCallのDomain・Infra実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/user/SaveUserService.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/account/Account.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/department/DepartmentRepository.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/hospital/HospitalRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/account/AccountPostTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/account/AccountTest.kt
Accountに係る、Role判定の実装。Model Repositoryの微修正
- Accountに自身がどのロールであるかを判定する処理を追加
- テスト追記
- RepositoryModelの微修正
- テストが通ること
> Accountのロール判定追加&Repositroy・Model微修正

- api-server/src/main/kotlin/com/unicorn/api/application_service/doctor/DoctorSaveService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/doctor/DoctorController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/doctor/DoctorPostTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/doctor/DoctorRepositoryTest.kt
- api-server/src/test/resources/db/doctor/Insert_Parent_Account_Data.sql
https://www.notion.so/POST-doctors-API-a7ce163d8bf2405388c0955f1770089e?pvs=4
- 医師登録APIの実装
- テスト記述
- テストが正常に通ること
> 医師登録APIの実装

- .idea/inspectionProfiles/Project_Default.xml
- api-server/src/main/kotlin/com/unicorn/api/application_service/doctor/DoctorUpdateService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/doctor/DoctorController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/doctor/DoctorPutTest.kt
https://www.notion.so/PUT-doctors-doctorID-API-39a4a33612c04fe294a5e11386caa842?pvs=4
- API実装
- テスト記述
- テストが通ること
> 医者情報更新APIの実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/doctor/DoctorDeleteService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/doctor/DoctorController.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/doctor/DoctorRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/doctor/DoctorDeleteTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/doctor/DoctorRepositoryTest.kt
https://www.notion.so/DELETE-doctors-doctorID-API-2175213db6d447b3963892a3730e3071?pvs=4
- API実装
- テスト記述
- Repository修正
- テストが通ること
> 医師削除APIの実装

- api-server/src/main/kotlin/com/unicorn/api/controller/doctor/DoctorController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/doctor/DoctorQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/doctor/DoctorGetTest.kt
https://www.notion.so/GET-doctors-doctorID-API-814f024668604d86bdb85d43096e0c0c?pvs=4
- API実装
- テスト記述
- テストが通ること
> doctorIDごとに医師情報を取得するAPIの実装

- api-server/src/main/kotlin/com/unicorn/api/controller/doctor/DoctorController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/doctor/DoctorQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/doctor/DoctorGetTest.kt
https://www.notion.so/GET-hospitals-hospitalID-doctors-API-0a16eb435b3a40b9a8c84121123b4eb7?pvs=4
- API実装
- テスト記述
- テストが正常に通ること
> 病院ごとの医師情報一括取得

- api-server/src/main/kotlin/com/unicorn/api/controller/doctor/DoctorController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/doctor/DoctorQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/doctor/DoctorGetTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/doctor/DoctorTest.kt
- api-server/src/test/resources/db/doctor/Insert_Temporary_Doctor_Data.sql
https://www.notion.so/GET-doctors-API-5ee3712b5b5641188d2ec272fb7b4826?pvs=4
- 医師検索APIの実装
- テスト記述
- テストが通ること
- 適切に絞り込みが行えること
> 医師検索APIの実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/health_checkup/SaveHealthCheckupService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupPostTest.kt
- 検査情報を登録できるAPIを実装する
- 検査情報が適切に登録できているかどうかを確認するテストを行う
- applicationServiceのSaveHealthCheckupService.ktを追加
- controllerのHealthCheckupController.ktを追加
- Postテストを行うHealthCheckupPostTest.ktを追加
- テストが通ったことを確認
- ローカル環境で登録できたことを確認
> [TSK-170] health_checkupのPOST機能追加

- api-server/src/main/kotlin/com/unicorn/api/application_service/health_checkup/UpdateHealthCheckupService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupPutTest.kt
- 検査情報を更新できるAPIを実装する
- 検査情報が適切に更新できているかどうかを確認するテストを行う
- ControllerにPUT機能を追加
- ApplicatonServiceにUpdateHealthCheckup.ktを追加
- putを行うテストファイルを追加
- テストが通ったことを確認。
- ローカル環境で更新処理ができたことを確認
> [TSK-172] health_checkupのPUT実装

- api-server/src/main/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/health_checkup/HealthCheckupQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupGetTest.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupPutTest.kt
- 検査情報を取得するAPIを実装する
- 検査情報が適切に取得できているかどうかを確認するテストを行う
- ControllerにhealthCheckupIDのGET機能追加
- QueryServiceのHealthCheckupQueryService.ktを追加
- healthCheckupIDのGETのテストを行うテストファイルを追加
- テストが通ることを確認
- ローカル環境で取得ができたことを確認
> [TKS-171] health_checkupのIDごとのGET機能実装

- api-server/build.gradle.kts
- api-server/src/main/kotlin/com/unicorn/api/config/WebSocketConfig.kt
WebSocketを用いてた双方向通信のための、Configファイル作成
- Conrigファイル作成
- 依存関係追加
- lintが通ること
> ChatAPIにおける、Websocket設定

- api-server/src/main/kotlin/com/unicorn/api/application_service/chat/SaveChatService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/chat/ChatController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/chat/ChatPostTest.kt
https://www.notion.so/POST-chats-API-fed2f5c8c39f4477a5546ef44586dcda?pvs=4
- Application Service, Controller実装
- テスト記述
- テストが通ること
> [POST] Chat 作成API実装 

- api-server/src/main/kotlin/com/unicorn/api/controller/chat/ChatController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/chat/ChatQueryService.kt
- api-server/src/main/kotlin/com/unicorn/api/util/ToJST.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/chat/ChatGetTest.kt
チャット情報の取得API実装
- API実装
- テスト記述
- テストが通ること
> [GET] Chat取得API実装

- api-server/build.gradle.kts
- api-server/src/main/kotlin/com/unicorn/api/application_service/message/SaveMessageService.kt
- api-server/src/main/kotlin/com/unicorn/api/config/SecurityConfig.kt
- api-server/src/main/kotlin/com/unicorn/api/config/WebSocketConfig.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/message/MessageController.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/message/MessageEventListener.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/message/MessageSavedEvent.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/message/MessageQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/message/MessagePostTest.kt
https://www.notion.so/POST-chats-chatID-messages-API-db308bfb733f49a8a17235c49d1ef566?pvs=4
- API実装
- EventListenerの実装
- Test記述
- テストが通ること
- ローカル動作確認
> メッセージ送信APIの実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/message/DeleteMessageService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/message/MessageController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/message/Message.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/message/MessageDeleteTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/message/MessageTest.kt
https://www.notion.so/DELETE-chats-chatID-messages-messageID-API-64aa9730b107433ea66979457d4d68d8?pvs=4
- 削除API実装
- テスト記述
- テストが通ること
> メッセージ削除API実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/account/UpdateAccountService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/account/AccountController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/account/Account.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/account/AccountRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/account/AccountPutTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/account/AccountTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/account/AccountRepositoryTest.kt
- api-spec/api-spec.yaml
- api-stub-server/api/openapi.yaml
このセクションでは、このPRの目的と概要を簡潔に説明してください。
- API実装
- テスト修正
- テストが通ること
> アカウント更新APIの実装

- api-server/src/main/kotlin/com/unicorn/api/domain/chronic_disease/ChronicDisease.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/chronic_disease/ChronicDiseaseRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/chromic_disease/ChromicDiseaseTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/chronic_disease/ChronicDiseaseRepositoryTest.kt
- api-server/src/test/resources/db/chronic_disease/Insert_Chronic_Disease_Data.sql
- 持病情報のdomainとrepositoryの実装をする
- 持病情報のdomainとrepositoryが動作しているかどうかを確認するテストを行う
- domainのChromicDisease.ktの追加
- repositoryのChromicDiseaseRepository.ktの追加
- それぞれのテストを行うテストファイルを追加
- テスト用のINSERT文SQLファイルを追加
- テストが通ったこと
> [TSK-221] chromic_diseaseのdomain・repositoryの実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/primary_doctor/SavePrimaryDoctorService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/primary_doctor/PrimaryDoctorController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/primary_doctor/PrimaryDoctor.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/primary_doctor/PrimaryDoctorPostTest.kt
- api-server/src/test/resources/db/primary_doctor/Insert_Doctor_Department_Data.sql
主治医情報登録機能の実装
- コントローラ層、サービス層の実装
- テストケースの実装
- ドメイン層の修正
- テストが通ること
> [TSK-167] primary_doctors 登録機能の実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/primary_doctor/UpdatePrimaryDoctorService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/primary_doctor/PrimaryDoctorController.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/primary_doctor/PrimaryDoctorRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/primary_doctor/PrimaryDoctorPutTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/primary_doctor/PrimaryDoctorRepositoryTest.kt
主治医情報更新機能の実装
- コントローラ層の追記とサービス層の実装
- 更新機能に関するテストケースの実装
- UserIDを使用したprimaryDoctor の絞り込みをリポジトリ層に追加
- テストが通ること。
> [TSK-168] primary_doctors 更新機能の実装とリポジトリ層の修正

- api-server/src/main/kotlin/com/unicorn/api/domain/doctor/Doctor.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/doctor/DoctorTest.kt
このセクションでは、このPRの目的と概要を簡潔に説明してください。
- 変更点1
- 変更点2
- 変更点3
> リリース　doctorの重複チェック

- api-server/src/main/kotlin/com/unicorn/api/application_service/chat/SaveChatService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/chat/ChatPostTest.kt
- RequestBodyをそのまま返却する実装から、chatモデルを返却する実装に変更
- テスト修正
- テストが通ること
> [POST] Chat APIのResponseにchatIDを含める

- .idea/codeStyles/codeStyleConfig.xml
- api-server/src/main/kotlin/com/unicorn/api/application_service/medicine/DeleteMedicineService.kt
- api-server/src/main/kotlin/com/unicorn/api/application_service/medicine/SaveMedicineService.kt
- api-server/src/main/kotlin/com/unicorn/api/application_service/medicine/UpdateMedicineService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/medicine/MedicineController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/medicine/Medicine.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/medicine_reminder/MedicineReminders.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/medicine/MedicineRepository.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/medicine_reminder/MedicineRemindersRepository.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/medicine/MedicineQueryService.kt
- api-server/src/main/resources/db/migration/V030__Create_Medicine_Reminder_Table.sql
- api-server/src/main/resources/db/migration/V031__Refactor_Medicine_Table.sql
- api-server/src/test/kotlin/com/unicorn/api/controller/medicine/MedicinePostTest.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/medicine/MedicinePutTest.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/medicine/MedicinesGetTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/medicine/MedicineTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/medicine_reminder/MedicineReminderTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/medicine/MedicineRepositoryTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/medicine_reminder/MedicineRemindersRepositoryTest.kt
- api-server/src/test/resources/db/medicine/Insert_Medicine_Data.sql
- api-server/src/test/resources/db/medicine_reminder/Insert_Medicine_Reminder_Data.sql
- Medicine APIに関わる、PUT, POST, DELETE, GETのAPI修正
- DDL追加
- テスト追加
- Domain, Application Service, Repository修正、追加
- Testが通ること
> Medicine APIのリファクタリング

- .circleci/config.yml
- README.md
- api-server/build.gradle.kts
- api-server/src/main/kotlin/com/unicorn/api/ApiServerApplication.kt
- api-server/src/main/kotlin/com/unicorn/api/application_service/health_checkup/SaveHealthCheckupService.kt
- api-server/src/main/kotlin/com/unicorn/api/application_service/health_checkup/SendMailHealthCheckupService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupEventListener.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/health_checkup/HealthCheckupSavedEvent.kt
- api-server/src/main/kotlin/com/unicorn/api/util/MailTransport.kt
- api-server/src/main/resources/application.properties
- api-server/src/test/kotlin/com/unicorn/api/controller/health_checkup/HealthCheckupPostTest.kt
検査結果が登録されたときにかかりつけ医にメールを送信する機能
- circleci変更
- readme変更
- javamail追加
- service追加
- controller追加
- domain追加
- application.properties変更
- テストが通ったこと
- ローカル環境でメールが送信されたこと
- 環境変数が追加されますので、忘れずに
> [リリース] 検査結果のメール送信

- api-spec/api-spec.yaml
- api-stub-server/api/openapi.yaml
- api-stub-server/controllers/Call.js
- api-stub-server/controllers/Medicine.js
- api-stub-server/controllers/User.js
- api-stub-server/package.json
- api-stub-server/service/AppConfigService.js
- api-stub-server/service/CallService.js
- api-stub-server/service/ChatService.js
- api-stub-server/service/ChronicDiseaseService.js
- api-stub-server/service/DepartmentService.js
- api-stub-server/service/DiseaseService.js
- api-stub-server/service/DoctorService.js
- api-stub-server/service/FamilyEmailService.js
- api-stub-server/service/HealthCheckupService.js
- api-stub-server/service/HospitalService.js
- api-stub-server/service/MedicineService.js
- api-stub-server/service/PrimaryDoctorsService.js
- api-stub-server/service/UserService.js
> [リリース] API YML

- api-server/build.gradle.kts
- api-server/src/main/kotlin/com/unicorn/api/application_service/family_email/SaveFamilyEmailService.kt
- api-server/src/main/kotlin/com/unicorn/api/application_service/family_email/UpdateFamilyEmailService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/disease/DiseaseController.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/family_email/FamilyEmailController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/family_email/FamilyEmail.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/family_email/FamilyEmailRepository.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/disease/DiseaseQueryService.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/family_email/FamilyEmailQueryService.kt
- api-server/src/main/resources/db/migration/V032__Refactor_FamilyEmails_Table.sql
- api-server/src/test/kotlin/com/unicorn/api/controller/family_email/FamilyEmailPostTest.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/family_email/FamilyEmailPutTest.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/family_email/FamilyEmailsGetTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/family_email/FamilyEmailTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/family_email/FamilyEmailRepositoryTest.kt
- api-server/src/test/resources/db/family_email/Insert_FamilyEmail_Data.sql
- api-spec/api-spec.yaml
- api-stub-server/api/openapi.yaml
- api-stub-server/package.json
- api-stub-server/service/FamilyEmailService.js
https://www.notion.so/family_email-a3e72f4911044fc7852a96a8b8c9cdb6?pvs=4
- SQL追加
- Swagger, Stub Server修正
- GET, POST PUTに関わる処理修正
- TEST修正
- Diseaseのpackeage移動←今回のタスクとは関係なし
- テストが通ること
- MIgrationが通ること
> Family Emailから電話番号を削除

- api-server/src/main/kotlin/com/unicorn/api/application_service/medicine/DeleteMedicineService.kt
- api-server/src/main/kotlin/com/unicorn/api/application_service/medicine/SaveMedicineService.kt
- api-server/src/main/kotlin/com/unicorn/api/application_service/medicine/UpdateMedicineService.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/medicine_reminders/MedicineReminders.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/medicine_reminders/MedicineRemindersRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/medicine_reminders/MedicineReminderTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/medicine_reminders/MedicineRemindersRepositoryTest.kt
パッケージ名でエラーになっていたので修正した
- パッケージ名修正
- テストが通ること
> medine reminder のパッケージ名修正

- api-server/src/main/kotlin/com/unicorn/api/controller/medicine/MedicineController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/medicine/MedicineQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/medicine/MedicineReminderGetTest.kt
- api-server/src/test/resources/db/medicine_reminder/Insert_Deleted_Medicine_Reminder_Data.sql
- api-spec/api-spec.yaml
- api-stub-server/api/openapi.yaml
- api-stub-server/controllers/Medicine.js
- api-stub-server/package.json
- api-stub-server/service/MedicineService.js
https://www.notion.so/GET-medicine-reminder-77f31eefe4b3416e9b56e5a33b5cd319?pvs=4
- APIの実装
- テスト追記
- Swagger, Stub Serverの修正
- テストが通ること
> [GET] Medicine Reminder APIの実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/medicine/DeleteMedicineService.kt
- api-server/src/main/kotlin/com/unicorn/api/application_service/medicine/SaveMedicineService.kt
- api-server/src/main/kotlin/com/unicorn/api/application_service/medicine/UpdateMedicineService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/medicine/MedicineController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/medicine_reminders/MedicineReminders.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/medicine_reminders/MedicineRemindersRepository.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/medicine/MedicineQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/medicine/MedicineReminderGetTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/medicine_reminders/MedicineReminderTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/medicine_reminders/MedicineRemindersRepositoryTest.kt
- api-server/src/test/resources/db/medicine_reminder/Insert_Deleted_Medicine_Reminder_Data.sql
- api-spec/api-spec.yaml
- api-stub-server/api/openapi.yaml
- api-stub-server/controllers/Medicine.js
- api-stub-server/package.json
- api-stub-server/service/MedicineService.js
https://github.com/unicorn-hal/unicorn-monorepo/pull/97
https://github.com/unicorn-hal/unicorn-monorepo/pull/98
> [Release] Medicine Reminder API

- api-server/src/main/kotlin/com/unicorn/api/domain/notification/Notification.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/notification/NotificationRepository.kt
- api-server/src/main/resources/db/migration/V034__Create_User_Notification_Table.sql
- api-server/src/test/kotlin/com/unicorn/api/domain/notification/NotificationTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/notification/NotificationRepositoryTest.kt
- api-server/src/test/resources/db/notification/Insert_Notification_Data.sql
通知APIのdomain・repository実装
- user_notificationsテーブルのCREATEファイル追加
- domainの追加
- repositoryの追加
- それぞれのテストファイル追加
- テストに使うINSERTファイル追加
- テストが通ったこと
> [TSK-241] 通知APIのdomain・repository実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/notification/SaveNotificationService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/notification/NotificationController.kt
- api-server/src/main/resources/db/migration/V034__Create_User_Notification_Table.sql
- api-server/src/test/kotlin/com/unicorn/api/controller/notification/NotificationPostTest.kt
通知APIの登録実装
- Controllerの追加
- ApplicationServiceの追加
- それぞれのテストの追加
- テストが通ること
- ローカル環境で登録ができたこと
> [TSK-243] 通知APIの登録実装

- api-server/src/main/kotlin/com/unicorn/api/controller/notification/NotificationController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/notification/NotificationQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/notification/NotificationGetTest.kt
通知APIの取得実装
- ControllerにGETを追加
- QueryService追加
- それぞれのテストを追加
- テストが通ったこと
- ローカル環境で取得できたこと
> [TSK-242] 通知APIの取得実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/family_email/SaveFamilyEmailService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/family_email/FamilyEmailController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/family_email/FamilyEmail.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/family_email/FamilyEmailPostTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/family_email/FamilyEmailTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/family_email/FamilyEmailRepositoryTest.kt
- api-spec/api-spec.yaml
- api-stub-server/api/openapi.yaml
- api-stub-server/package.json
- api-stub-server/service/FamilyEmailService.js
https://discord.com/channels/1276167084895637526/1306423527217299537/1307668443650068480
- テスト追加
- Application Serviceの改修
- Domainの改修
-  テストが通ること
> FamilyEmailIDをRequestBodyから受け取るように修正

- api-server/src/main/kotlin/com/unicorn/api/controller/app_config/AppConfigController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/app_config/AppConfigQueryService.kt
- api-server/src/main/resources/db/migration/V035__Create_AppConfig_Table.sql
- api-server/src/main/resources/db/migration/V036__Refactor_AppConfig_Table.sql
- api-server/src/test/kotlin/com/unicorn/api/controller/app_config/AppConfigGetTest.kt
- api-server/src/test/resources/db/app_config/Insert_AppConfig_False.sql
- api-server/src/test/resources/db/app_config/Insert_AppConfig_True.sql
appConfigにSTUNサーバーの向き先切り替えを行うためstun追加
- enumのstun作成ファイル追加
- app_configテーブルにstun追加
- ControllerのAvailableResponse削除
- QueryServiceにstun取得追加
- テストにstun取得追加
- テストが通ること
- ローカル環境で取得できたこと
> [TSK-238] appConfigにstun追加

- api-server/src/main/kotlin/com/unicorn/api/application_service/call/SaveCallService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/call/CallController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/call/service/CallDomainService.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/call/CallRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/call/CallPostTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/call/service/CallDomainServiceTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/call/CallRepositoryTest.kt
- api-server/src/test/resources/db/call/Insert_New_Call_Data.sql
通話予約追加機能の実装
- CallController, SaveCallService の実装
- テストケースの実装
- テストが通ること
> [TSK-197] 通話予約追加機能の実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/call/DeleteCallService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/call/CallController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/call/CallDeleteTest.kt
通話予約情報 削除機能の実装
- コントローラ層に追記
- DeleteCallService の実装
- テストケースの実装
- テストが通ること
> [TSK-199] 通話予約情報 削除機能の実装

- api-server/src/main/kotlin/com/unicorn/api/controller/call/CallController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/call/CallQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/call/CallGetByCallReservationID.kt
- api-spec/api-spec.yaml
- api-stub-server/api/openapi.yaml
- api-stub-server/controllers/Call.js
- api-stub-server/package.json
- api-stub-server/service/CallService.js
要望
https://discord.com/channels/1276167084895637526/1306423527217299537/1310241300817121340
- API実装
- テスト記述
- テストが通ること
> [GET] Call/CallReservationID APIの実装

- api-server/src/main/kotlin/com/unicorn/api/controller/app_config/AppConfigController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/app_config/AppConfigQueryService.kt
- api-server/src/main/resources/db/migration/V035__Refactor_App_Config_Table.sql
- api-server/src/test/kotlin/com/unicorn/api/controller/app_config/AppConfigGetTest.kt
- api-server/src/test/resources/db/app_config/Insert_AppConfig_False.sql
- api-server/src/test/resources/db/app_config/Insert_AppConfig_True.sql
- api-spec/api-spec.yaml
- api-stub-server/api/openapi.yaml
- api-stub-server/service/AppConfigService.js
https://discord.com/channels/1276167084895637526/1311531349290651741/1311531946136047707
- APi実装
- テスト修正
- YAML追加
- テストが通ること
- DBに値を追加
> App ConfigにRelease Build プロパティを追加

- api-server/src/main/resources/db/migration/V036__Refactor_Role_Type.sql
- api-server/src/main/resources/db/migration/V037__Create_Status_Type.sql
- api-server/src/main/resources/db/migration/V038__Create_Robots_Table.sql
- api-server/src/main/resources/db/migration/V039__Create_Emergency_Queue_Table.sql
- api-server/src/main/resources/db/migration/V040__Create_Robot_Supports_Table.sql
ロボット要請に関わる3つのDBテーブルの作成
- Create文のsqlを追加しました
- accountsのroleにrobotを追加しました
- flywayのマイグレートが通ったこと
> [TSK-265] ロボット要請に関わるDBテーブル作成

- api-server/src/main/resources/db/migration/V41__Create_HospitalNews_Table.sql
- api-server/src/main/resources/db/migration/V42__Refactor_HospitalNews_Table.sql
hospital_news テーブルの CREATE 文の作成
- V41__Create_HospitalNews_Table.sql の作成
> [TSK-266] hospital_news テーブルの作成

- api-server/src/main/kotlin/com/unicorn/api/domain/emergency/Emergency.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/emergency/EmergencyRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/emergency/EmergencyTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/emergency/EmergencyRepositoryTest.kt
- api-server/src/test/resources/db/emergency/Insert_Emergency_Data.sql
emergencyAPIのdomainとrepository実装
- domainの追加
- repositoryの追加
- それぞれのテスト追加
- Insert分のsqlファイル追加
- テストが通ったこと
> [TSK-267] emergencyAPIのdomainとrepository実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/hospital_news/DeleteHospitalNewsService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/hospital_news/HospitalNewsController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/hospital_news/HospitalNewsDeleteTest.kt
hospital_news 削除機能の実装
- HospitalNewsController の実装
- DeleteHospitalNewsService の実装
- テストの追加
- テストが通ること
> [TSK-262] hospital_news 削除機能の実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/hospital_news/SaveHospitalNewsService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/hospital_news/HospitalNewsController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/hospital_news/HospitalNewsPostTest.kt
病院お知らせ 登録機能の実装
- HospitalNewsController に追記
- SaveHospitalNewsService を実装
- テストの実装
- テストが通ること
- 
> [TSK-263] hospital_news 登録機能の実装

- api-server/src/main/kotlin/com/unicorn/api/domain/medicine/Medicine.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/medicine/MedicinePostTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/medicine/MedicineTest.kt
medicine の quantity を 0 許容に変更
- Medicine.kt 内の Quantity の仕様を変更
- テストの修正
- テストが通ること
> fix: medicine の quantity を 0 許容に変更

- api-server/src/main/kotlin/com/unicorn/api/application_service/message/SaveMessageService.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/account/Account.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/robot/Robot.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/message/MessageQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/message/MessagePostTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/account/AccountTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/robot/RobotTest.kt
- api-server/src/test/resources/db/message/Insert_Parent_Account_Data.sql
https://www.notion.so/Account-e698aff8a8134efe8d55d8d85e494254?pvs=4
- Account修正
- Robot微修正
-  ローカルでの動作確認
-  テストが通ること
> Robot追加に係るAccount修正&微修正

- api-server/src/main/kotlin/com/unicorn/api/application_service/robot/SaveRobotService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/robot/RobotController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/robot/RobotPostTest.kt
- api-server/src/test/resources/db/robot/Insert_User_Account_Data.sql
https://www.notion.so/bef116b0d016417fb3ec2699e7644832?v=ea59308459f14c6f8d22d90a4b67b001&p=5909bc6b346a41a38442d6180be98ac1&pm=s
- Robot 保存API実装
- テスト記述
- テストが通ること
> Robot POST API実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/robot/SaveRobotService.kt
- api-server/src/main/kotlin/com/unicorn/api/application_service/robot/UpdateRobotService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/robot/RobotController.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/robot/RobotRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/robot/RobotPostTest.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/robot/RobotPutTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/robot/RobotRepositoryTest.kt
- api-server/src/test/resources/db/robot/Insert_User_Account_Data.sql
https://www.notion.so/Robot-PUT-a3e87b7fa3214d90aae7e49cbc26f679?pvs=4
- ロボット更新API実装
- ロボット作成APIの微修正
- テスト追加
- テストが通ること
> ロボット更新API実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/robot/DeleteRobotService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/robot/RobotController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/robot/RobotDeleteTest.kt
https://www.notion.so/Robot-Delete-db1e9f1ff7bd4755a31a1bab77de335d?pvs=4
- 削除APIの実装
- テスト記述
- テストが通ること
> ロボット削除APIの実装

- api-server/src/main/kotlin/com/unicorn/api/controller/robot/RobotController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/robot/RobotQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/robot/RobotGetTest.kt
https://www.notion.so/Robot-Get-f6f7b8a2a19d4c7ca2c46603bffc26dd?pvs=4
- GET API実装
- テスト記述
- テストが通ること
> ロボット情報取得API実装

- api-server/src/main/kotlin/com/unicorn/api/query_service/doctor/DoctorQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/doctor/DoctorGetTest.kt
- Doctor Departmentがdeleted_atで除外されていない問題を修正
- テスト修正
- ローカルでの動作確認
- deleted_atで除外されること
> doctor_departmentがdeleted_atで除外されていない問題を修正

- api-server/src/main/kotlin/com/unicorn/api/controller/call/CallController.kt
- api-server/src/main/kotlin/com/unicorn/api/query_service/call/CallQueryService.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/call/CallGetByUserIDTest.kt
UserID を使用した call reservation の取得機能の実装
https://discordapp.com/channels/1276167084895637526/1314205053325938709
- CallController に追記
- CallQueryService に追記
- 新規テストの実装
- テストが通ること
> UserID を使用した call reservation の取得機能の実装

- api-server/src/main/kotlin/com/unicorn/api/query_service/call/CallQueryService.kt
同じ departments が繰り返し返されてしまう問題を修正
- CallQueryService の fun getByUserID() の sql を修正
- テストが通ること
> fix: 同じ departments が繰り返し返されてしまう問題を修正

- api-server/src/main/kotlin/com/unicorn/api/application_service/complete/NotifyCompleteService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/complete/ConmpleteController.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/emergency/EmergencyEventListener.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/complete/PostCompleteTest.kt
unicorn要請の完了API実装
- Controller追加
- ApplicationService追加
- ControllerTest追加
- テストが通ったこと
- ローカル環境で期待通りの動きをしたこと
> [TSK-286] 完了通知API実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/complete/NotifyCompleteService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/complete/ConmpleteController.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/emergency/EmergencyEventListener.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/complete/PostCompleteTest.kt
unicorn要請の完了API実装
- 変更点1
- 変更点2
- 変更点3
> [リリース] 完了通知API

- api-server/src/main/kotlin/com/unicorn/api/application_service/moving/NotifyMovingService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/moving/MovingController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/moving/PostMovingTest.kt
unicorn要請の移動通知APIの実装
- Controller追加
- ApplicationService追加
- Controllerのテスト追加
- テストが通ったこと
- ローカル環境で動作したこと
> [TSK-284] 移動通知API実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/moving/NotifyMovingService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/moving/MovingController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/moving/PostMovingTest.kt
unicorn要請の移動通知API実装
- 変更点1
- 変更点2
- 変更点3
> [リリース] 移動通知API実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/arrival/NotifyArrivalService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/arrival/ArrivalController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/arrival/PostArrivalTest.kt
unicorn要請の到着通知APIの実装
- Controller追加
- ApplicationService追加
- Controllerテストの追加
- テストが通ったこと
- ローカル環境で動作したこと
> [TSK-285] 到着通知APIの実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/arrival/NotifyArrivalService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/arrival/ArrivalController.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/arrival/PostArrivalTest.kt
unicorn要請の到着通知APIの実装
- 変更点1
- 変更点2
- 変更点3
> [リリース]到着通知APIの実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/primary_doctor/DeletePrimaryDoctorService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/primary_doctor/PrimaryDoctorController.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/primary_doctor/PrimaryDoctorRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/primary_doctor/PrimaryDoctorDeleteTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/primary_doctor/PrimaryDoctorRepositoryTest.kt
PrimaryDoctorIDを参照して削除処理を行っていた部分を、DoctorIDを参照するように変更
- repositoryに新たに関数追加
- Controllerを変更
- ApplicationServiceを変更
- それぞれのテストに追加
- テストが通ったこと
> [THS-294] DoctorIDでPrimaryDoctorを削除

- api-server/src/main/kotlin/com/unicorn/api/application_service/emergency/RobotRequestService.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/robot/Robot.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/unicorn_status/EmergencyUserStatus.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/robot/RobotRepository.kt
- api-server/src/main/resources/db/migration/V043__Refactor_RobotStatus_Type.sql
- api-server/src/test/kotlin/com/unicorn/api/domain/robot/RobotTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/unicorn_status/EmergencyUserStatusTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/robot/RobotRepositoryTest.kt
- api-server/src/test/resources/db/robot/Insert_Robot_Shutdown_Data.sql
RobotStatusにshutdownを追加し、全員shutdownだった場合の処理を追加
- RobotDomain変更
- RobotRepository変更
- EmergencyUserStatus変更
- RobotRequestService変更
- それぞれのテスト追加
- テストで使うInsertファイル追加
- テストが通ったこと
> [TSK-296] RobotStatusにshutdown実装

- api-server/src/main/kotlin/com/unicorn/api/application_service/robot/UpdateRobotStatusService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/robot/RobotController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/robot/Robot.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/robot/RobotGetTest.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/robot/RobotPowerPutTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/robot/RobotTest.kt
- api-server/src/test/resources/db/robot/Insert_Parent_Account_Data.sql
- api-server/src/test/resources/db/robot/Insert_Robot_Data.sql
https://www.notion.so/PUT-robot-robotID-power-5eae54a879254556ad154d6307d9e177?pvs=4
- Domainにpowerを追加
- Controller, Serviceの追加
- テスト追加
- テストが通ること
> [PUT] robots/{robotID}/power

- api-server/src/main/kotlin/com/unicorn/api/application_service/emergency/RobotRequestService.kt
- api-server/src/main/kotlin/com/unicorn/api/application_service/robot/UpdateRobotStatusService.kt
- api-server/src/main/kotlin/com/unicorn/api/controller/robot/RobotController.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/robot/Robot.kt
- api-server/src/main/kotlin/com/unicorn/api/domain/unicorn_status/EmergencyUserStatus.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/robot/RobotRepository.kt
- api-server/src/main/resources/db/migration/V043__Refactor_RobotStatus_Type.sql
- api-server/src/test/kotlin/com/unicorn/api/controller/robot/RobotGetTest.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/robot/RobotPowerPutTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/robot/RobotTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/unicorn_status/EmergencyUserStatusTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/robot/RobotRepositoryTest.kt
- api-server/src/test/resources/db/robot/Insert_Parent_Account_Data.sql
- api-server/src/test/resources/db/robot/Insert_Robot_Data.sql
- api-server/src/test/resources/db/robot/Insert_Robot_Shutdown_Data.sql
> [release]ロボットの電源制御

- api-spec/api-spec.yaml
- api-stub-server/api/openapi.yaml
- api-stub-server/controllers/Firebase.js
- api-stub-server/controllers/PrimaryDoctors.js
- api-stub-server/controllers/Robot.js
- api-stub-server/package.json
- api-stub-server/service/FirebaseService.js
- api-stub-server/service/PrimaryDoctorsService.js
- api-stub-server/service/RobotService.js
このセクションでは、このPRの目的と概要を簡潔に説明してください。
- 変更点1
- 変更点2
- 変更点3
> [リリース] 緊急要請時に家族とかかりつけ医にメール送信

- api-server/src/main/kotlin/com/unicorn/api/domain/robot/Robot.kt
- api-server/src/main/kotlin/com/unicorn/api/infrastructure/robot/RobotRepository.kt
- api-server/src/test/kotlin/com/unicorn/api/controller/robot/RobotPowerPutTest.kt
- api-server/src/test/kotlin/com/unicorn/api/domain/robot/RobotTest.kt
- api-server/src/test/kotlin/com/unicorn/api/infrastructure/robot/RobotRepositoryTest.kt
アプリ部からの依頼で、Swaggerに合わせるためRobotdomainのrobotStatusをstatusに変更
- robotStatusをstatusに変更
- テストが通ったこと
- ローカル環境でstatusで返ってきたこと
> [TSK-299] robotStatusからstatusに変更
